### ISSUE TITLE
Assignment Review

### ISSUE THREAD

**Issue by Jailbreak7587** [cankatmis/layered-CRUD-application#2]
Hello,

I checked the code and it mostly meets the specified requirements, however It does not contain a Console app that communicates with the API so in it's current form I can not accept it. But if you add the Console app before the final deadline next week then it will be accepted. Other noteworthy things to check because in their current form you would receive minus points for them are:
- Some tests are pointless.
- Naming could be improved upon.

Roland

**Comment by cankatmis** [comment]
Hello,

Thank you for your response. Can you expand it a little bit because I can
run my application in a browser without any problems. In addition to that,
which of my unit tests were pointless so that I can work on them as well.

Sincerely,
Can Katmış

Jailbreak7587 ***@***.***>, 2 Ara 2022 Cum, 17:35 tarihinde
şunu yazdı:

**Comment by cankatmis** [comment]
Sorry for the misunderstanding, I have added my client part to the project
and fetch origin to github. Could you please check it? Also, I checked the
namings and I was sensitive while giving the names, I changed the database
name. If you are talking about the Classes part, it basically means a class
such as mathematics, history etc. It might seem confusing but that was the
best name to give.

Sincerely yours,
Can Katmış

can katmis ***@***.***>, 2 Ara 2022 Cum, 17:46 tarihinde şunu yazdı:

**Comment by Jailbreak7587** [comment]
It looks okay now. you will get the 20 points.
